use_frameworks!

platform :ios, '12.0'

target 'TProgressHUD_Example' do
  pod 'TProgressHUD', :path => '../'

  target 'TProgressHUD_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
  end
 end
end
